* Common
** Decision-support system
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 23, 272
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

Rule based reminder system.


** Trigger
SCHEDULED: <2016-04-13 Wed 23:15>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 440
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

A user enters an order.


* Clinical stream
** Patient
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 388, 185
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

Patients admitted to the general-medicine service of one hospital.


** Clinical knowledge

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

*** #1
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 335
:END:

National guidelines regarding the use of 5 therapies.

*** #2
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 61, 287
:END:

Influenza seasonality.


** Patient data

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

*** #1
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 195
:END:

Routinely collected data such demographic characteristics, lists of medical
problems etc.

*** #2
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 167
:END:

Information from vaccination status by standard admission questionnaire.


** Clinical conclusions
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 261, 613
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

Membership of patient group at risk, and appropriate preventive therapy and
argumentation.


** Clinical advice
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 299, 402
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

Whether to order, choice of prescription, and default value with regards to
acceptance or rejection.


* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-13 Wed 23:15>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 39, 483
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

Resident physicians and medical students on the general-medicine team that write
all orders.


** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 148, 581
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

Need to communicate in natural language; need for explanation of reasoning; need
to specify order.


** User data
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 299, 473
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

A user either accepts or rejects a recommendation.


** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 364, 520
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

User should order preventitive care for patient.


** Presentation
*** Content
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 198, 527
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

Recommendations phrased in natural language.


*** Timing
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 60, 133
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

The alerts could have been generated earlier than the moment of ordering by
user.


*** Channel
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 54, 471
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

Integrated into order-entry program.


*** Format
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 298, 516
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

Plain text.


*** Notification
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 306, 646
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

User receives reminder after neglecting the first opportunity.


*** Interaction functions
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 145, 649
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

User may pick 'order', 'revise' or 'omit'.


