* Common
** Decision-support system
SCHEDULED: <2016-04-19 Tue 11:52>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 23, 272
:END:

#+BEGIN_QUOTE
Developer checklist:
Knowledge representation and reasoning mechanisms to be used.
#+END_QUOTE

'Order Entry Gopher'; Rule based reminder system.

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

** Trigger
SCHEDULED: <2016-04-13 Wed 23:15>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 440
:END:

#+BEGIN_QUOTE
Developer checklist:
Data or interaction that triggers the system to begin processing.
#+END_QUOTE

A user enters an order.

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

** TODO Organizational/Environmental factors

#+BEGIN_QUOTE
Developer checklist:
Factors that affect the implementation or adoption of decision support systems
in general, such as the 'Meaningful Use' plan.
#+END_QUOTE

** TODO Study factors

#+BEGIN_QUOTE
Developer checklist:
Factors that affect the outcome of the study but do not reflect on the decision
support system itself, such as poor study power or contamination of the control
group)
#+END_QUOTE

** TODO Empirical measures

#+BEGIN_QUOTE
Developer checklist:
Measured usage, usability, etc.
#+END_QUOTE

* Clinical stream
** Patient
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 388, 185
:END:

#+BEGIN_QUOTE
Developer checklist:
- Patient population.
- Relevant attributes (chief complaint, history of present illness, problem
  list, preferences, wish to be involved in decisions, etc.)
#+END_QUOTE

Patients admitted to the general-medicine service of one hospital.

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

** Clinical knowledge

#+BEGIN_QUOTE
Developer checklist:
Source(s) and types of clinical knowledge required.
#+END_QUOTE

*** #1
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 335
:END:

National guidelines regarding the use of 5 therapies.

*** #2
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 61, 287
:END:

Influenza seasonality.

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

** Patient data

#+BEGIN_QUOTE
Developer checklist:
Data elements:
- Sources and types of data elements.
- Interpretation/action if data element is missing.
#+END_QUOTE

*** #1
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 195
:END:

Routinely collected data such demographic characteristics, lists of medical
problems etc.

*** #2
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 167
:END:

Information from vaccination status by standard admission questionnaire.

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

** Clinical conclusions
SCHEDULED: <2016-04-19 Tue 11:52>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 261, 613
:END:

#+BEGIN_QUOTE
Developer checklist:
Types of conclusions the system can draw.
#+END_QUOTE

Membership of patient group at risk, and appropriate preventive therapy and
argumentation.

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

** Clinical advice
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 299, 402
:END:

#+BEGIN_QUOTE
Developer checklist:
Types and wording of advice the system can present.
#+END_QUOTE

Whether to order, choice of prescription, and default value with regards to
acceptance or rejection.

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-13 Wed 23:15>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 39, 483
:END:

#+BEGIN_QUOTE
Developer checklist:
- Role (patient, patientþdoctor, junior doctor, specialist, etc.).
- Setting (home, ward, ICU, etc.).
- Clinical workflow (clinical activity and tasks).
- Cognitive workflow (sequence of data capture and reasoning).
#+END_QUOTE

Resident physicians and medical students on the general-medicine team that write
all orders.

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-19 Tue 11:52>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 148, 581
:END:

#+BEGIN_QUOTE
Developer checklist:
- Anticipated usage/workflow.
- Theory/strategy for support (expected utility, prospect theory, behavior
  change, etc.)
#+END_QUOTE

Need to communicate in natural language; need for explanation of reasoning; need
to specify order.

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

** User data
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 299, 473
:END:

#+BEGIN_QUOTE
Developer checklist:
- Static data (eg, role, supervisor, preferences)
- Dynamic data (mouse clicks, response to previous alerts, etc.).
#+END_QUOTE

A user either accepts or rejects a recommendation.

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 364, 520
:END:

#+BEGIN_QUOTE
Developer checklist:
Conclusions that the system can draw about the user.
#+END_QUOTE

User should order preventitive care for patient.

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

** Presentation
*** Content

#+BEGIN_QUOTE
Developer checklist:
Content (eg, framing)
#+END_QUOTE

**** #1
SCHEDULED: <2016-04-19 Tue 11:52>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 63, 423
:END:

Prewritten orders with explanatory text.

**** #2
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 198, 527
:END:

Recommendations phrased in natural language.

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

*** Timing
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 60, 133
:END:

#+BEGIN_QUOTE
Developer checklist:
Timing
#+END_QUOTE

The alerts could have been generated earlier than the moment of ordering by
user.

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

*** Channel
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 54, 471
:END:

#+BEGIN_QUOTE
Developer checklist:
Channel
#+END_QUOTE

Integrated into order-entry program.

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

*** Format
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 298, 516
:END:

#+BEGIN_QUOTE
Developer checklist:
Format
#+END_QUOTE

Plain text.

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

*** Notification
SCHEDULED: <2016-04-13 Wed 23:05>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 306, 646
:END:

#+BEGIN_QUOTE
Developer checklist:
Notification
#+END_QUOTE

User receives reminder after neglecting the first opportunity.

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

*** Interaction functions

#+BEGIN_QUOTE
Developer checklist:
Interaction functions
#+END_QUOTE

**** #1
SCHEDULED: <2016-04-19 Tue 11:52>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 62, 402
:END:

User can accept or reject a reminder with one or two keystrokes.

**** #2
SCHEDULED: <2016-04-19 Tue 11:52>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 145, 649
:END:

User may pick 'order', 'revise' or 'omit'.

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

