* Common
** Decision-support system
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 336, 154
:END:

#+BEGIN_QUOTE
Developer checklist:
Knowledge representation and reasoning mechanisms to be used.
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

** Trigger
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 354, 105
:END:

#+BEGIN_QUOTE
Developer checklist:
Data or interaction that triggers the system to begin processing.
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

** TODO Organizational/Environmental factors

#+BEGIN_QUOTE
Developer checklist:
Factors that affect the implementation or adoption of decision support systems
in general, such as the 'Meaningful Use' plan.
#+END_QUOTE

** TODO Study factors

#+BEGIN_QUOTE
Developer checklist:
Factors that affect the outcome of the study but do not reflect on the decision
support system itself, such as poor study power or contamination of the control
group)
#+END_QUOTE

** TODO Empirical measures

#+BEGIN_QUOTE
Developer checklist:
Measured usage, usability, etc.
#+END_QUOTE

* Clinical stream
** Patient
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 133, 490
:END:

#+BEGIN_QUOTE
Developer checklist:
- Patient population.
- Relevant attributes (chief complaint, history of present illness, problem
  list, preferences, wish to be involved in decisions, etc.)
#+END_QUOTE

Women undergoing ovarian stimulation to treat infertility.

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

** Clinical knowledge
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 16, 525
:END:

#+BEGIN_QUOTE
Developer checklist:
Source(s) and types of clinical knowledge required.
#+END_QUOTE

Average hormone (FSH, LH) levels and ratios

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

** Patient data

#+BEGIN_QUOTE
Developer checklist:
Data elements:
- Sources and types of data elements.
- Interpretation/action if data element is missing.
#+END_QUOTE

*** #1
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 279, 315
:END:

Regimen used, hormone levels, pelvic ultrasonography results, results of
previous cycles, protocol used.

*** #2
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 279, 206
:END:

Patient age, number of treated cycles, cause of infertility.

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

** Clinical conclusions
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 279, 626
:END:

#+BEGIN_QUOTE
Developer checklist:
Types of conclusions the system can draw.
#+END_QUOTE

Classification of patient ovaries FSH simulation response

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

** Clinical advice
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 279, 242
:END:

#+BEGIN_QUOTE
Developer checklist:
Types and wording of advice the system can present.
#+END_QUOTE

Drug management

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 279, 536
:END:

#+BEGIN_QUOTE
Developer checklist:
- Role (patient, patientþdoctor, junior doctor, specialist, etc.).
- Setting (home, ward, ICU, etc.).
- Clinical workflow (clinical activity and tasks).
- Cognitive workflow (sequence of data capture and reasoning).
#+END_QUOTE

N/A, only the performers of the therapy are mentioned.

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 127, 190
:END:

#+BEGIN_QUOTE
Developer checklist:
- Anticipated usage/workflow.
- Theory/strategy for support (expected utility, prospect theory, behavior
  change, etc.)
#+END_QUOTE

Need for expertise regarding FSH use; need to carefully monitor therapy.

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

** User data
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 540, 431
:END:

#+BEGIN_QUOTE
Developer checklist:
- Static data (eg, role, supervisor, preferences)
- Dynamic data (mouse clicks, response to previous alerts, etc.).
#+END_QUOTE

Text input from user regarding therapy results

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 156, 570
:END:

#+BEGIN_QUOTE
Developer checklist:
Conclusions that the system can draw about the user.
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

** Presentation
*** Content
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 410, 129
:END:

#+BEGIN_QUOTE
Developer checklist:
Content (eg, framing)
#+END_QUOTE

Software has sections with patient identity, fertility variables, monitoring of
ovarian stimulation, end of cycle data, and statistical data.

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

*** Timing
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 236, 104
:END:

#+BEGIN_QUOTE
Developer checklist:
Timing
#+END_QUOTE

N/A, no information regarding the display timing of the recommendation to the
user.

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

*** Channel
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 439, 182
:END:

#+BEGIN_QUOTE
Developer checklist:
Channel
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

*** Format
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 466, 180
:END:

#+BEGIN_QUOTE
Developer checklist:
Format
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

*** Notification
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 237, 68
:END:

#+BEGIN_QUOTE
Developer checklist:
Notification
#+END_QUOTE

N/A, no information regarding the display timing of the recommendation to the
user.

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

*** Interaction functions
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 539, 376
:END:

#+BEGIN_QUOTE
Developer checklist:
Interaction functions
#+END_QUOTE

N/A, the only mentioned input occurs at the end of the cycle, not during a
decision support process.

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

