* Common
** Decision-support system
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 336, 154
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

N/A


** Trigger
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 354, 105
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

N/A


* Clinical stream
** Patient
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 133, 490
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

Women undergoing ovarian stimulation to treat infertility.


** Clinical knowledge
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 16, 525
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

Average hormone (FSH, LH) levels and ratios


** Patient data

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

*** #1
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 279, 315
:END:

Regimen used, hormone levels, pelvic ultrasonography results, results of
previous cycles, protocol used.

*** #2
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 279, 206
:END:

Patient age, number of treated cycles, cause of infertility.


** Clinical conclusions
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 279, 626
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

Classification of patient ovaries FSH simulation response


** Clinical advice
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 279, 242
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

Drug management


* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 279, 536
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

N/A, only the performers of the therapy are mentioned.


** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 127, 190
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

Need for expertise regarding FSH use; need to carefully monitor therapy.


** User data
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 540, 431
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

Text input from user regarding therapy results


** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 156, 570
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

N/A


** Presentation
*** Content
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 410, 129
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

Software has sections with patient identity, fertility variables, monitoring of
ovarian stimulation, end of cycle data, and statistical data.


*** Timing
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 236, 104
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

N/A, no information regarding the display timing of the recommendation to the
user.


*** Channel
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 439, 182
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

N/A


*** Format
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 466, 180
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

N/A


*** Notification
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 237, 68
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

N/A, no information regarding the display timing of the recommendation to the
user.


*** Interaction functions
SCHEDULED: <2016-04-14 Thu 15:32>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 539, 376
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

N/A, the only mentioned input occurs at the end of the cycle, not during a
decision support process.


