* Common
** Decision-support system
SCHEDULED: <2016-04-18 Mon 16:08>
:PROPERTIES:
:PAGE: 2
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

Custom system


** TODO Trigger

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

* Clinical stream
** Patient
SCHEDULED: <2016-04-18 Mon 15:55>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

Patient from asthma register of GP.


** Clinical knowledge
SCHEDULED: <2016-04-18 Mon 15:56>
:PROPERTIES:
:PAGE: 2
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

Bank of clinical scenarios and constructive feedback; Future morbidity
prediction patient database.


** TODO Patient data

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

** TODO Clinical conclusions

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

** Clinical advice

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

*** #1
SCHEDULED: <2016-04-18 Mon 16:29>
:PROPERTIES:
:PAGE: 6
:END:

Management recommendations and reminders.

*** #2
SCHEDULED: <2016-04-18 Mon 16:30>
:PROPERTIES:
:PAGE: 6
:END:

Risk prediction.


* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-18 Mon 15:55>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

General practitioners that use a Microsoft Windows computer during consultations
who wished to test new software, approached through advertisements in medical
press.


** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-18 Mon 16:22>
:PROPERTIES:
:PAGE: 2
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

Need to collect data; need to adhere to agreed pathway; need to respond to
certain triggers.


** User data
SCHEDULED: <2016-04-18 Mon 16:27>
:PROPERTIES:
:PAGE: 2
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

Data entered at consultation by the user.


** TODO Cognitive-behavioral conclusions

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

** Presentation
*** Content
SCHEDULED: <2016-04-18 Mon 16:11>
:PROPERTIES:
:PAGE: 2
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

Comments and advice phrased in natural language.


*** TODO Timing

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

*** Channel
SCHEDULED: <2016-04-18 Mon 16:18>
:PROPERTIES:
:PAGE: 9
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

Stand-alone system.


*** Format
SCHEDULED: <2016-04-18 Mon 16:17>
:PROPERTIES:
:PAGE: 2
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

Print and others.


*** TODO Notification

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

*** TODO Interaction functions

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

