* Common
** Decision-support system
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 343
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

Custom system


** Trigger
SCHEDULED: <2016-04-19 Tue 14:02>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 16, 207
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

Data entered during consultation.


* Clinical stream
** Patient
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 362, 427
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

Patient from asthma register of GP.


** Clinical knowledge
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 147
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

Bank of clinical scenarios and constructive feedback; Future morbidity
prediction patient database.


** Patient data
SCHEDULED: <2016-04-19 Tue 14:01>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 11, 165
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

N/A


** Clinical conclusions
SCHEDULED: <2016-04-19 Tue 14:01>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 15, 117
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

N/A


** Clinical advice

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

*** #1
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 7
:COORDINATES: 395, 618
:END:

Management recommendations and reminders.

*** #2
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 7
:COORDINATES: 395, 571
:END:

Risk prediction.


* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 395, 546
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

General practitioners that use a Microsoft Windows computer during consultations
who wished to test new software, approached through advertisements in medical
press.


** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 439
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

Need to collect data; need to adhere to agreed pathway; need to respond to
certain triggers.


** User data
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 224
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

Data entered at consultation by the user.


** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-19 Tue 14:03>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 14, 83
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

N/A


** Presentation
*** Content
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 164
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

Comments and advice phrased in natural language.


*** Timing
SCHEDULED: <2016-04-19 Tue 14:03>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 13, 187
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

Immediate.


*** Channel
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 10
:COORDINATES: 395, 415
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

Stand-alone system.


*** Format
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 398, 73
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

Print and others.


*** Notification
SCHEDULED: <2016-04-19 Tue 14:04>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 397, 55
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

N/A


*** Interaction functions
SCHEDULED: <2016-04-19 Tue 14:04>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 19, 40
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

N/A


