* Common
** Decision-support system
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 343
:END:

#+BEGIN_QUOTE
Developer checklist:
Knowledge representation and reasoning mechanisms to be used.
#+END_QUOTE

Custom system

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

** Trigger
SCHEDULED: <2016-04-19 Tue 14:02>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 16, 207
:END:

#+BEGIN_QUOTE
Developer checklist:
Data or interaction that triggers the system to begin processing.
#+END_QUOTE

Data entered during consultation.

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

** TODO Organizational/Environmental factors

#+BEGIN_QUOTE
Developer checklist:
Factors that affect the implementation or adoption of decision support systems
in general, such as the 'Meaningful Use' plan.
#+END_QUOTE

** TODO Study factors

#+BEGIN_QUOTE
Developer checklist:
Factors that affect the outcome of the study but do not reflect on the decision
support system itself, such as poor study power or contamination of the control
group)
#+END_QUOTE

** TODO Empirical measures

#+BEGIN_QUOTE
Developer checklist:
Measured usage, usability, etc.
#+END_QUOTE

* Clinical stream
** Patient
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 362, 427
:END:

#+BEGIN_QUOTE
Developer checklist:
- Patient population.
- Relevant attributes (chief complaint, history of present illness, problem
  list, preferences, wish to be involved in decisions, etc.)
#+END_QUOTE

Patient from asthma register of GP.

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

** Clinical knowledge
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 147
:END:

#+BEGIN_QUOTE
Developer checklist:
Source(s) and types of clinical knowledge required.
#+END_QUOTE

Bank of clinical scenarios and constructive feedback; Future morbidity
prediction patient database.

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

** Patient data
SCHEDULED: <2016-04-19 Tue 14:01>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 11, 165
:END:

#+BEGIN_QUOTE
Developer checklist:
Data elements:
- Sources and types of data elements.
- Interpretation/action if data element is missing.
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

** Clinical conclusions
SCHEDULED: <2016-04-19 Tue 14:01>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 15, 117
:END:

#+BEGIN_QUOTE
Developer checklist:
Types of conclusions the system can draw.
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

** Clinical advice

#+BEGIN_QUOTE
Developer checklist:
Types and wording of advice the system can present.
#+END_QUOTE

*** #1
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 7
:COORDINATES: 395, 618
:END:

Management recommendations and reminders.

*** #2
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 7
:COORDINATES: 395, 571
:END:

Risk prediction.

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 395, 546
:END:

#+BEGIN_QUOTE
Developer checklist:
- Role (patient, patientþdoctor, junior doctor, specialist, etc.).
- Setting (home, ward, ICU, etc.).
- Clinical workflow (clinical activity and tasks).
- Cognitive workflow (sequence of data capture and reasoning).
#+END_QUOTE

General practitioners that use a Microsoft Windows computer during consultations
who wished to test new software, approached through advertisements in medical
press.

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 439
:END:

#+BEGIN_QUOTE
Developer checklist:
- Anticipated usage/workflow.
- Theory/strategy for support (expected utility, prospect theory, behavior
  change, etc.)
#+END_QUOTE

Need to collect data; need to adhere to agreed pathway; need to respond to
certain triggers.

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

** User data
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 224
:END:

#+BEGIN_QUOTE
Developer checklist:
- Static data (eg, role, supervisor, preferences)
- Dynamic data (mouse clicks, response to previous alerts, etc.).
#+END_QUOTE

Data entered at consultation by the user.

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-19 Tue 14:03>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 14, 83
:END:

#+BEGIN_QUOTE
Developer checklist:
Conclusions that the system can draw about the user.
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

** Presentation
*** Content
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 395, 164
:END:

#+BEGIN_QUOTE
Developer checklist:
Content (eg, framing)
#+END_QUOTE

Comments and advice phrased in natural language.

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

*** Timing
SCHEDULED: <2016-04-19 Tue 14:03>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 13, 187
:END:

#+BEGIN_QUOTE
Developer checklist:
Timing
#+END_QUOTE

Immediate.

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

*** Channel
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 10
:COORDINATES: 395, 415
:END:

#+BEGIN_QUOTE
Developer checklist:
Channel
#+END_QUOTE

Stand-alone system.

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

*** Format
SCHEDULED: <2016-04-18 Mon 16:32>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 398, 73
:END:

#+BEGIN_QUOTE
Developer checklist:
Format
#+END_QUOTE

Print and others.

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

*** Notification
SCHEDULED: <2016-04-19 Tue 14:04>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 397, 55
:END:

#+BEGIN_QUOTE
Developer checklist:
Notification
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

*** Interaction functions
SCHEDULED: <2016-04-19 Tue 14:04>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 19, 40
:END:

#+BEGIN_QUOTE
Developer checklist:
Interaction functions
#+END_QUOTE

N/A

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

