* Common
** Decision-support system
SCHEDULED: <2016-04-18 Mon 17:32>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

Contains encoded suggestions.


** Trigger
SCHEDULED: <2016-04-18 Mon 17:34>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

Suggestions are identified after visit from patient.


* Clinical stream
** Patient
SCHEDULED: <2016-04-18 Mon 17:00>
:PROPERTIES:
:PAGE: 0
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

Patients with uncomplicated hypertension.


** Clinical knowledge
SCHEDULED: <2016-04-18 Mon 17:38>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

Evidence-based guidelines on hypertension, adjusted for use in system by
clinical experts.


** Patient data
SCHEDULED: <2016-04-18 Mon 17:28>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

Patients' EMR and data entered by user.


** Clinical conclusions
SCHEDULED: <2016-04-18 Mon 17:58>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

Approriate order suggestions.


** Clinical advice
SCHEDULED: <2016-04-18 Mon 17:57>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

What to order with rationale.


* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-18 Mon 17:08>
:PROPERTIES:
:PAGE: 2
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

Physicians and pharmacists.


** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-18 Mon 18:08>
:PROPERTIES:
:PAGE: 1
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

Need to make updated information (such as guidelines) available to user.


** User data
SCHEDULED: <2016-04-18 Mon 17:30>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

Acts upon the suggestions by the system (e.g. order, omit, etc.).


** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-18 Mon 18:08>
:PROPERTIES:
:PAGE: 4
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

User accepts or rejects suggestions.


** Presentation
*** Content
SCHEDULED: <2016-04-18 Mon 17:21>
:PROPERTIES:
:PAGE: 4
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

Recommendations phrased in natural language.


*** Timing
SCHEDULED: <2016-04-18 Mon 17:25>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

The suggestions are displayed to the user during order entry.


*** Channel
SCHEDULED: <2016-04-18 Mon 17:12>
:PROPERTIES:
:PAGE: 3
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

Integrated into order-entry program.


*** Format
SCHEDULED: <2016-04-18 Mon 17:21>
:PROPERTIES:
:PAGE: 4
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

Plain text.


*** Notification
SCHEDULED: <2016-04-18 Mon 18:00>
:PROPERTIES:
:PAGE: 4
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

Direct display.


*** Interaction functions

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

**** #1
SCHEDULED: <2016-04-18 Mon 17:27>
:PROPERTIES:
:PAGE: 3
:END:

User can list full guidelines and literature citations by pressing 'help' key.

**** #2
SCHEDULED: <2016-04-18 Mon 17:27>
:PROPERTIES:
:PAGE: 4
:END:

User may order, revise, D/C, renew or take no action.


