* Common
** Decision-support system
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 300, 431
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

Rule based reminder program.


** Trigger
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 28, 25
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

User enters a 'trigger' order.


* Clinical stream
** Patient
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 11
:COORDINATES: 286, 501
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

Hospitalized in interal medicine at one institution.


** Clinical knowledge

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

*** #1
SCHEDULED: <2016-04-14 Thu 21:13>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 294, 159
:END:

Standard reference texts, drug package inserts.

*** #2
SCHEDULED: <2016-04-14 Thu 21:13>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 291, 27
:END:

Drug utilization review criteria developed independtly by clinical experts.


** Patient data
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 289, 108
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

Demographic information, diagnoses and problem lists, inpatient and outpatient
visits, admitting history and physical examination reports, discharge summaries,
vital signs, immunizations given, nearly all diagnostic test results (including
serologies, cervical cytology, and mammograms), procedures, and outpatient
prescriptions


** Clinical conclusions
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 293, 404
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

Appropriate corollary orders.


** Clinical advice
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 295, 502
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

Order recommendations with reasoning and dose


* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 32, 58
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

Medicine physicians that place orders.


** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-14 Thu 21:13>
:PROPERTIES:
:PAGE: 2
:COORDINATES: 289, 624
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

Need to reduce order omissions errors during inpatient stays.


** User data
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 293, 334
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

Acceptance, rejection or modification per recommended order.


** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 293, 281
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

User should respond to the recommendations.


** Presentation
*** Content
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 241, 547
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

Recommendations phrased in natural language.


*** Timing
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 292, 365
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

Immediate.


*** Channel
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 15, 43
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

Integrated into computer order entry system.


*** Format
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 420, 510
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

Plain text


*** Notification
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 292, 385
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

Direct display.


*** Interaction functions
SCHEDULED: <2016-04-14 Thu 21:39>
:PROPERTIES:
:PAGE: 4
:COORDINATES: 169, 534
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

User can select one choice per order.


