* Common
** Decision-support system
SCHEDULED: <2016-04-19 Tue 12:01>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 36, 232
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Rules represented as LISP expressions and an associated inference engine.
#+END_EXAMPLE

'Order Entry Gopher'


** Trigger
SCHEDULED: <2016-04-19 Tue 12:09>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 295, 467
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Initiated by a user seeking advice (clinician).
#+END_EXAMPLE

Physician entered data about patient.


* Clinical stream
** Patient
SCHEDULED: <2016-04-19 Tue 11:39>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 29, 413
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Hospitalized patients with severe bacterial infections.
- Demographics, allergies, background conditions (eg., compromised host?), etc.
#+END_EXAMPLE

Outpatients with heart failure and/or ischemic heart disease.


** Clinical knowledge
SCHEDULED: <2016-04-19 Tue 11:41>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 22, 373
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Clinical experts.
- Bacterial identification and empirical antibiotic choice.
#+END_EXAMPLE

Evidence-based cardiac care suggestions, approved by panel of local
cardiologists and general internists.


** Patient data
SCHEDULED: <2016-04-19 Tue 12:04>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 22, 500
:END:

#+BEGIN_EXAMPLE
MYCIN example:
- Gender, age, current diagnosis, vital signs, bacterial morphology, culture
  site, etc.
- Entered by user (not integrated with EHR).
#+END_EXAMPLE

From EMR, includes demographics, visit information, diagnoses, drugs, diagnostic
test results (both numeric and coded text of imaging study reports), and vital
signs.


** Clinical conclusions
SCHEDULED: <2016-04-19 Tue 12:51>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 299, 652
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Identity of organism, underlying inferences, and degree of certainty.
#+END_EXAMPLE

N/A


** Clinical advice
SCHEDULED: <2016-04-19 Tue 12:48>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 294, 513
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Whether to treat, choice of antibiotic(s), and strength of recommendation.
#+END_EXAMPLE

Variety of patient-specific feedback about various clinical issues.


* Cognitive-behavioral stream
** User(s)
SCHEDULED: <2016-04-19 Tue 11:40>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 30, 441
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Clinician(s) requiring infectious disease consultation (expertise in other
areas).
#+END_EXAMPLE

Primary care physicians and pharmacists.


** Cognitive-behavioral knowledge
SCHEDULED: <2016-04-19 Tue 11:43>
:PROPERTIES:
:PAGE: 1
:COORDINATES: 29, 506
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Need to communicate in natural language; need for explanation of reasoning; need
to manage and convey uncertainty.
#+END_EXAMPLE

Need to reduce errors of commission and omission.


** User data
SCHEDULED: <2016-04-19 Tue 12:09>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 299, 493
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Text input from user (eg, answering simple questions, entering data, user enters
“why” or “how”).
#+END_EXAMPLE

Input by physician, such as vital signs, symptoms, and NYHA class.


** Cognitive-behavioral conclusions
SCHEDULED: <2016-04-19 Tue 12:52>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 293, 584
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User wants advice, an explanation, or help.
#+END_EXAMPLE

N/A


** Presentation
*** Content
SCHEDULED: <2016-04-19 Tue 12:45>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 176, 178
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Conclusion and advice phrased in natural language
#+END_EXAMPLE

Suggested orders with details phrased in natural language.


*** Timing
SCHEDULED: <2016-04-19 Tue 12:10>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 291, 429
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Immediate
#+END_EXAMPLE

Immediate.


*** Channel
SCHEDULED: <2016-04-19 Tue 12:11>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 292, 385
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Stand-alone system
#+END_EXAMPLE

Integrated into order system.


*** Format
SCHEDULED: <2016-04-19 Tue 12:11>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 290, 408
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Plain text
#+END_EXAMPLE

Plain text.


*** Notification
SCHEDULED: <2016-04-19 Tue 12:45>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 294, 447
:END:

#+BEGIN_EXAMPLE
MYCIN example:
Direct display
#+END_EXAMPLE

Direct display


*** Interaction functions
SCHEDULED: <2016-04-19 Tue 12:12>
:PROPERTIES:
:PAGE: 3
:COORDINATES: 293, 364
:END:

#+BEGIN_EXAMPLE
MYCIN example:
User may type “why” or “how” for explanation
#+END_EXAMPLE

Accept, revise, deny order etc.; Ask for help, escape to avoid all suggestions.


